### ISSUE TITLE
Compiled version

### ISSUE THREAD

**Issue by vadi2** [andreikop/qutepart#63]
Is it possible to compile qutepart so there's no runtime dependency on a Python install? I'm interested in embedding this in a Qt C++ application.

**Comment by andreikop** [comment]
Hi
Theoretically it might be possible to build Qutepart which uses libpython.so for it's work. But I'm afraid you'll face so many problems that is is easier to switch your application to Python or rewrite Qutepart in pure C++.

Try to look at KTextEditor
