### ISSUE TITLE
PySide Support

### ISSUE THREAD

**Issue by jbeukelman** [andreikop/qutepart#64]
Your documentation states this control is for PyQt and Pyside, but I'm not seeing how this would work with PySide.  

#34 mentions there is a PySide branch, but I'm not seeing it.  Has the PySide branch been discontinued?

Thanks!

**Comment by bjones1** [comment]
As far as I know, the pyside branch was dropped when Enki was ported to Python 3.x / Qt 5.x. Looking at https://wiki.qt.io/PySide2, is seems like PySide is still lagging Qt releases. Current (development) Enki relies on Qt 5.8. Until there's better support from PySide, I don't think this is possible.

**Comment by jbeukelman** [comment]
You're right, the latest version could not be ported to PySide.  PySide2 work is progressing but it looks like a stable release is still a ways out.  
Perhaps I'll grab the 2.2.3 code and see if I can port it myself.

**Comment by bjones1** [comment]
Sounds good!
