### ISSUE TITLE
test_vim.py fails with Aborted (core dumped) if built with python 3.7

### ISSUE THREAD

**Issue by rapgro** [andreikop/qutepart#69]
Several tests of test_vm.py fail, for instance CopyPaste. Regression of #50?
We run the tests in xvfb. All tests with success and python 3.6.5 .

**Comment by andreikop** [comment]
It seems like it is bad idea to try to get UI tests working on PyQt.
Current tests consume much more time than save.
Can you just disable test run?

**Comment by rapgro** [comment]
You might be right about slow execution of tests and we should disable (at least) those slow tests. Next point is that all tests run in some framebuffer environment via xvfb. All in all, the tests are implemented on a very high level with a lot of components that could fail and lead to a crash.
We currently have Qt 5.11.1 in Fedora Rawhide if this information is of any help. Though, we don't see the crashes with Qt 5.11.1 and Python 3.6.5, as already stated.

**Comment by andreikop** [comment]
Just disable the tests.
They work on PC with X server, and I won't support it on xvfb.
