### ISSUE TITLE
reStructuredText highlighting issue

### ISSUE THREAD

**Issue by kechap** [andreikop/qutepart#70]
The reStructuredText highlighting is not working as expected. 

As you can see in the following images when there is formatted text inside a paragraph or you just prepend whitespace the text is not getting highlighted.

I firstly thought this might be the desired behavior so I tested kate editor. The result is the following:

**kate**
--
![kate](https://user-images.githubusercontent.com/899436/43832619-ae8b247a-9b10-11e8-8b48-63a3927ac461.PNG)

**qutepart**
--
![qutepart](https://user-images.githubusercontent.com/899436/43832620-aeaa49e0-9b10-11e8-861f-5763d5b395cf.PNG)

**Comment by andreikop** [comment]
It seems like I've found the bug.
I'll pull updated syntax highlighting definitions from the upstream.

**Comment by andreikop** [comment]
@kechap , could you please check the bug on current qutepart master?

**Comment by kechap** [comment]
@andreikop I tried the latest master but I am getting the same result.

**Comment by andreikop** [comment]
Yes, I see

Snippet for further tests
```
.. This is a test

this is bold **bold text**
**bold text** 
```

**Comment by kechap** [comment]
I think that the fix broke something else now. The styling is applied to other text also. See the following output

![hl](https://user-images.githubusercontent.com/899436/44724718-38f66900-aadc-11e8-8372-cba9940421b1.png)


Snippet for tests

```Here, **code-block** is the name of the directive. **html** is an argument telling that the code is in HTML format, **lineos** is an option telling to insert line number and finally after a blank line is the text to include.

Here, *code-block* is the name of the directive. *html* is an argument telling that the code is in HTML format, *lineos* is an option telling to insert line number and finally after a blank line is the text to include.

Here, ``code-block`` is the name of the directive. ``html`` is an argument telling that the code is in HTML format, ``lineos`` is an option telling to insert line number and finally after a blank line is the text to include.
```

**Comment by andreikop** [comment]
This is independent bug which always existed. (Actually TODO)
I've fixed it. But only for binary version of the parser. (when C extension is used)
