### ISSUE TITLE
Prefer system icons over bundled ones

### ISSUE THREAD

**Issue by sscherfke** [andreikop/qutepart#72]
qutepart would look nicer/more integrated if the system’s icons (`QIcon.fromTheme()`) would be used.  The bundled icons can be used as a fallback.

I could create a PR if this is something you’d like to change.

**Comment by andreikop** [comment]
Hi.
Good idea, PR is welcome!

**Comment by sscherfke** [comment]
What do you think about updating the bundled icons with the latest Breeze version? Breeze is the default KDE icon theme and IMHO, the icons look good and neutral enough for other systems, too.

![qutepart-icons](https://user-images.githubusercontent.com/511179/45942513-065c6500-bfe3-11e8-98e4-ba3a9c86a737.png)

**Comment by andreikop** [comment]
Yes, I like this theme

**Comment by sscherfke** [comment]
Okay, but I need to check their license first.

**Comment by sscherfke** [comment]
Breeze Icons use LGPL 3.0, so it should be no problem. I’ll add a notice to the directory.

**Comment by sscherfke** [comment]
Do you have any objections or suggestions for the PR or can it be merged? :)
