### ISSUE TITLE
Calling setLineWrapMode does not update the side area

### ISSUE THREAD

**Issue by sscherfke** [andreikop/qutepart#75]
When you call `setLineWrapMode(mode)` (e.g., via a checkable `QAction`), the side area (line numbers, ...) is not updated. It is only updated when you resize the window or when you call `update()` manually:

```python
class Editor(Qutepart)
    ...

    def set_word_wrap(self, do_wrap):
        mode = self.WidgetWidth if do_wrap else self.NoWrap
        self.setLineWrapMode(mode)
        self.update()  # Force side area to update itself
```

**Comment by andreikop** [comment]
Qutepart doesn't expose set_word_wrap method. So, it is rather Qt bug. I think your fix is good enough and it doesn't make sense to workaround the bug in Qutepart

**Comment by sscherfke** [comment]
Maybe, Qutepart can override this method like this in order to trigger a sidearea re-draw?

```python
    def setLineWrapMode(self, mode):
        super().setLineWrapMode(mode)
        self.update()
```

**Comment by andreikop** [comment]
In this case Qutepart will have to support this code in the future.
Who know, maybe Qt will fix the problem, or add new params to the method, or ...

Make this workaround in your code.
