### ISSUE TITLE
Python files use Windows line endings (\r\n), not just \n

### ISSUE THREAD

**Issue by sscherfke** [andreikop/qutepart#77]
The python files in the released tarball have Windows line endings (`\r\n`) and not unix line endings (`\n`). This is very surprising as most packages use the latter.

Is this intentional? For me, it looks like the git repo uses Unix line endings (but maybe the Git client automatically converts line endings on Linux?).

Anyway, using Windows line endings leads to problems with some tools, e.g., when applying patches that contain Unix line endings (which is the default that most tools use).

**Comment by andreikop** [comment]
Which download link you use and which file has \r\n.
I downloaded zip and tar.gz using Releases page and checked Makefile and qutepart/__init__.py. It seems like they have \n.
But I will not be surprised if github, archive manager or some other software converts EOLs.

**Comment by sscherfke** [comment]
I downloaded this file from PyPI: https://files.pythonhosted.org/packages/d3/8d/02ae2e73bab6325ab095620c658021bd967ca0756d86490544d85a848b1a/qutepart-3.2.0.tar.gz

**Comment by andreikop** [comment]
Fixed.
But I don't have any idea how I initially managed to create a package with Windows EOLs
