### ISSUE TITLE
python 3.10 needs explicit float-to-int casting

### ISSUE THREAD

**Issue by rapgro** [andreikop/qutepart#91]
https://github.com/andreikop/qutepart/blob/089b2c9d60a37663f37275b3ecddb95c9edba2a2/qutepart/margins.py#L76

No idea but height() gives a float when compiled with python 3.10

Please use instead a workaround as in
`blockHeight = int(self._qpart.blockBoundingRect(self._qpart.firstVisibleBlock()).height())`

**Comment by andreikop** [comment]
Hi
I've fixed the bug and tagged a version
Checkout master
